# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28156e908a49fe79fa278a6baf25352e0f63e0a5ac5b885b13345ea3c6d34d591aeccc7a5ed06e5f43a6bcf66f5d539f1523d165a2faf7d325284f157e319467

test:
  secret_key_base: 13bf4714554887bfe0bf935fff1608bd601e1734aaa0361c76ca003c1709e2376cff4c71ed91e188c71a56e84ba2c75724bc944b4a66e73ebee3b7f74725c68f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
